### PR TITLE
[EXP-29-229] Brownie bridge: gRPC integration

### PR DESCRIPTION
**Pull request by mariuspod**
In this PR I've exposed brownie functionality via gRPC.
By opening multiple channels it's possible to do async multi-chain calls.

Currently, it's only returning token prices from the exporter, but it's quite easy to extend to other methods as well.

## Build

set `WEB3_PROVIDER`, `EXPLORER`, `FTM_WEB3_PROVIDER`, `FTM_EXPLORER` envs

launch it with : `make bb-rebuild`

## Usage for js clients:

`npm install https://github.com/mariuspod/yrpc.git`

sample js client:

https://github.com/mariuspod/yrpc/blob/main/sample_client.js

We can run the following snippet to get all prices for the given tokens for all chains:
```javascript
require('dotenv').config();
const { YearnExporter, grpc } = require("./yrpc");

const host = process.env.HOST || 'localhost';
const ethPort = process.env.ETH_PORT || 1337;
const ftmPort = process.env.FTM_PORT || 1338;

// TODO add secure channel example
const ethClient = new YearnExporter(`${host}:${ethPort}`, grpc.credentials.createInsecure());
const ftmClient = new YearnExporter(`${host}:${ftmPort}`, grpc.credentials.createInsecure());

/**
 * this is a sample client requesting the prices for several contracts over gRPC. 
 */

const ethAddresses = [
  "0x0bc529c00c6401aef6d220be8c6ea1667f6ad93e",
].map(a => ({ address: a, network: "mainnet" }));

const ftmAddresses = [
  "0x29b0Da86e484E1C0029B56e817912d778aC0EC69",
].map(a => ({ address: a, network: "ftm-main" }));

call(ethClient, ethAddresses);
call(ftmClient, ftmAddresses);

function call(client, addresses) {
  const call = client.GetPrices({addresses: addresses});
  console.log("calling yearn_exporter.getPrices()...");
  call.on('data', function(address) {
    console.log(address);
  });
}
```

### CODE REVIEW

**Comment by mariuspod** [comment]
linked task in Web project: https://linear.app/yearn/issue/WEB-1325/[web-1325-216]-add-exporter-pricing-service

**Review by BobTheBuidler — APPROVED** [review]
It might be good to add some tests, but approving this in current state

**Comment by BobTheBuidler** [comment]
Per discussion with @mariuspod leaving this unmerged until further notice.

**Comment by mariuspod** [comment]
closing this until there is a more suitable service infra for this usecase

**Pull request closed without merging**
