### PR TITLE
[EXP-82-282] added qidao's dai and ftm vaults

### PR DESCRIPTION
**Pull request by publu**

### CODE REVIEW

**Comment by BobTheBuidler** [comment]
While testing other Fantom PRs, I found an issue with batch calls on Fantom.
I've implemented a quick fix for this issue in https://github.com/yearn/yearn-exporter/pull/281.
Placing this on hold until 281 is merged.

**Comment by BobTheBuidler** [comment]
@publu  #285  fixes the above mentioned issue. 
I tested your pr after rebasing on master, and noticed you added your vaults in the Network.Mainnet section of the partners var. 
You're going to need to add your wrappers in the appropriate Network section.
Everything else looks good, just update that and we should be all set!

**Comment by publu** [comment]
ok its now in the right area, thanks!

**Comment by BobTheBuidler** [comment]
There's something wrong going on here, please review: https://github.com/yearn/yearn-exporter/pull/282/commits/3b6c751e54af98f0dd9e1fec172aeecf26af5e7b

**Comment by publu** [comment]
fixed the merging issue

**Review by BobTheBuidler — APPROVED** [review]
Fixed one more syntax error and now lgtm

**Pull request merged**
