### PR TITLE
Fix peso

### PR DESCRIPTION
**Pull request by BobTheBuidler**

### CODE REVIEW

**Review by mariuspod — COMMENTED** [review]
fix is good, but we have ERC20 interfaces in `/interfaces` already.
Do we need to import it from an external dependency ?

**Review by mariuspod — APPROVED** [review]

**Comment by mariuspod** [comment]
you could do something like this: https://github.com/yearn/yearn-exporter/blob/9f3117b14ac9b4df37578ec7f36b5df0ab8e5a0a/yearn/__init__.py#L20-L24

**Comment by BobTheBuidler** [comment]
The dependency is already going to be included as part of #420, and after that point it would make sense to use the convenience method provided by ypricemagic.

**Comment by BobTheBuidler** [comment]
merging after discussion with @mariuspod

**Pull request merged**
