### PR TITLE
fix: use crypto swap registry if available

### PR DESCRIPTION
**Pull request by jstashh**
Fixes https://github.com/yearn/yearn-exporter/issues/187

Check to see if the 'CryptoSwap' registry can be used before falling back to the original registry

The crypto swap registry can be found at position 5 in the address provider

### CODE REVIEW

**Comment by jstashh** [comment]
Gauge isn't currently being provided by the curve crypto swap registry.. Have let them know and waiting for a response

**Review by mariuspod — APPROVED** [review]
I've tested this locally and it returns now the correct prices:

```
>>> curve.get_price("0x3D229E1B4faab62F621eF2F6A610961f7BD7b23B", 13907523)
2.129874676823631
>>> curve.get_price("0x3D229E1B4faab62F621eF2F6A610961f7BD7b23B", 13907516)
2.129874676823631
>>> curve.get_price("0x3b6831c0077a1e44ed0a21841c3bc4dc11bce833", 13907523)
2.1665122547780067
>>> curve.get_price("0x3b6831c0077a1e44ed0a21841c3bc4dc11bce833", 13907516)
2.1665122547780067
```

**Comment by mariuspod** [comment]
> Gauge isn't currently being provided by the curve crypto swap registry.. Have let them know and waiting for a response

@jstashh Is this a blocker for this merge ?

**Comment by jstashh** [comment]
> > Gauge isn't currently being provided by the curve crypto swap registry.. Have let them know and waiting for a response
> 
> @jstashh Is this a blocker for this merge ?

No, this should be fine to merge now, the incorrect gauge behavior is present in the current code so we're not introducing a regression

**Pull request merged**
