### PR TITLE
[EXP-28-228] Add avalanche support

### PR DESCRIPTION
**Pull request by 0xbeary**
### Description

Support avax #228.

Not sure about the chainlink price feeds mapping, or what else is necessary to be done.

### CODE REVIEW

**Comment by BobTheBuidler** [comment]
@0xbeary re: chainlink, can you format them like the ones for Fantom? So you'll have 2 addresses on each line, the left address will be the asset address, and the right address will be the feed address

**Comment by BobTheBuidler** [comment]
We will also need to:
- [ ] configure avax-specific constants in yearn/prices/constants.py
- [ ] configure "end" block for scripts/historical-exporter.py
- [ ] test the exporters on avax to ensure that things work, its possible that I'm forgetting something critical in the above comments

**Comment by 0xbeary** [comment]
> 



> 

Thanks Bob! Think I addressed most of your concerns. Unsure about a few things though:
1. How many assets to include in price feeds?
2. `ib_snapshot_block_by_network` what  to put for a new network? Similar in `historical_exporter.py`?
3. Are there instructions on testing a new network?

**Comment by 0xbeary** [comment]
> We will also need to:
> 
>     * [ ]  configure avax-specific constants in yearn/prices/constants.py
> 
>     * [ ]  configure "end" block for scripts/historical-exporter.py
> 
>     * [ ]  test the exporters on avax to ensure that things work, its possible that I'm forgetting something critical in the above comments and we don't want to push a flawed PR to master


Thanks Bob! Think I addressed most of your concerns. Unsure about a few things though:
1. How many assets to include in price feeds?
2. `ib_snapshot_block_by_network` what  to put for a new network? Similar in `historical_exporter.py`?
3. Are there instructions on testing a new network?

**Comment by 0xkofee** [comment]
I am working on adding gnosis support. There are not readme's that I found. But essentially you need to get a script working I think. For example: `brownie run tvl` works with my changes. You would need to work through all the problems that come up one by one.

**Comment by BobTheBuidler** [comment]
I just created a PR that will add a checklist for adding new chains. 

Could you take a peek at the checklist here and make sure you've got everything?

https://github.com/yearn/yearn-exporter/pull/242/files

**Comment by BobTheBuidler** [comment]
> > We will also need to:
> > ```
> > * [ ]  configure avax-specific constants in yearn/prices/constants.py
> > 
> > * [ ]  configure "end" block for scripts/historical-exporter.py
> > 
> > * [ ]  test the exporters on avax to ensure that things work, its possible that I'm forgetting something critical in the above comments and we don't want to push a flawed PR to master
> > ```
> 
> Thanks Bob! Think I addressed most of your concerns. Unsure about a few things though:
> 
> 1. How many assets to include in price feeds?
> 2. `ib_snapshot_block_by_network` what  to put for a new network? Similar in `historical_exporter.py`?
> 3. Are there instructions on testing a new network?

1: I would include all available feeds when setting up a new chain
2: since IB is not deployed on Avax, you can put a 1
3: I've included some basic instructions for testing in the checklist I linked above. LMK if you run into issues, we can always improve upon the instructions

**Comment by BobTheBuidler** [comment]
@0xbeary were you able to get the avax exporters up and running successfully?

**Comment by 0xbeary** [comment]
Closing this. No time to work sorry.

**Comment by dylan5394** [comment]
@BobTheBuidler I am looking into finishing this work up. Isn't this [ticket](https://github.com/yearn/yearn-exporter/issues/228) just asking to set up scaffolding for AVAX? There were no contract addresses provided in the ticket so it seems there would be no TVL exports to test for AVAX yet.

**Pull request closed without merging**
