### PR TITLE
[EXP-41-242] feat: add-a-chain.md instructions for adapting y-e to a new chain

### PR DESCRIPTION
**Pull request by BobTheBuidler**

### CODE REVIEW

**Comment by BobTheBuidler** [comment]
@mariuspod do you see anything I missed?

**Comment by banteg** [comment]
maybe this could be a template issue?
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates

**Review by mariuspod — CHANGES_REQUESTED** [review]
@BobTheBuidler 
Wow, that's really quite a lot that needs to be adapted, thanks for writing that down!

What's missing IMO:

- in Makefile:
- [ ] add entries to `new-chain-builld`, `new-chain-up`, `new-chain-down`, `new-chain-rebuild`


I agree with banteg we could try to use gh issue templates for this. If that doesn't work well for some reason, we could ask contributors to copy this template file on their branch and rename it to their chain and then they can tick the things they've already done.

**Comment by 0xkofee** [comment]
> @BobTheBuidler Wow, that's really quite a lot that needs to be adapted, thanks for writing that down!
> 
> What's missing IMO:
> 
>     * in Makefile:
> 
>     * [ ]  add entries to `new-chain-builld`, `new-chain-up`, `new-chain-down`, `new-chain-rebuild`
> 
> 
> I agree with banteg we could try to use gh issue templates for this. If that doesn't work well for some reason, we could ask contributors to copy this template file on their branch and rename it to their chain and then they can tick the things they've already done.

I don't think I saw any chain specific stuff in the makefile... Not sure if that is a separate feature

**Comment by mariuspod** [comment]
@0xkofee you're right, atm there aren't any network-aware recipes in the Makefile. However, as we're adding more and more new ones, this could be beneficial for us because soon it won't be possible to run all exporters for all networks on a single dev machine unless you have lots of free RAM. The memory footprint of a single exporter is currently pretty high at 4-8GB depending mostly on the amount of contracts it needs to keep in memory, so this varies a lot by network.

The other alternative we've discussed was to have Makefile recipes for each service type and run it for all networks that support it.

Currently this is all WIP and in the design phase, so feel free to take my comment as a suggestion to start with one solution and evaluate it for further usage.

I'll start with the re-structuring of the Makefile soon on a separate branch.

**Comment by 0xkofee** [comment]
@mariuspod I guess what is the problem with setting the env variables to context switch between chains?

**Comment by BobTheBuidler** [comment]
@mariuspod when you write `new-chain-up` do you mean for the contributor to explicitly hardcode the new chain name, ie `avax-up` `arb-up` etc?

**Comment by DarkGhost7** [comment]
in ./yearn/networks.py: `ib_snapshot_block_by_network` might be good to keep up to date?

**Comment by DarkGhost7** [comment]
in yearn/treasury/treasury.py update start_block with the first trx's block of the strategist multisig trx listed

**Comment by DarkGhost7** [comment]
Fixes #433 & #432 #428

**Pull request closed without merging**
