### PR TITLE
feat(docker): use python:3.9.7-slim package and multi-stage build for…

### PR DESCRIPTION
**Pull request by mariuspod**
… smaller docker image sizes. Added workflow for publishing GitHub Packages for default branch.

Reduced the docker image size from 1.18GB to 300MB

Needs some more testing :joy:

### CODE REVIEW

**Comment by mariuspod** [comment]
@nymmrx 
in this PR I've setup the workflow for building the docker image based on slim.
It's triggered whenever a commit is pushed to master branch either directly or by merging a PR into it.
The docker image is named:
`ghcr.io/yearn/yearn-exporter:latest`

which is the most convenient because we can then leave the tag out and just use:

`ghcr.io/yearn/yearn-exporter`


Here's the first image I created via a workflow:
https://github.com/yearn/yearn-exporter/pkgs/container/yearn-exporter


I've also adapted the deploy.sh so that we can just use the pre-built image when deploying and do not have to do it in the deploy.sh anymore.

**Comment by mariuspod** [comment]
just realized that it might have happened that we deployed the older image because we had two separate workflows. Merged them now into one with two steps: `build` and `deployment`

**Comment by mariuspod** [comment]
@nymmrx just rebased to master and tested locally with the `python:3.9.7-slim` image.

**Comment by bsamuels453** [comment]
fyi bumping the docker image to python 3.9 fixes the following error in transaction-exporter on master:
`[00:41<00:00, 417kiB/s][33] Error loading Python lib '/tmp/_MEIYmu9AT/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29' not found (required by /tmp/_MEIYmu9AT/libpython3.8.so.1.0)
`

**Comment by mariuspod** [comment]
@bsamuels453 
thanks, the GLIBC error is already fixed by this: affa923185ebec1afa5c97d82df682b786f9f38e

Will update this PR soon.

**Comment by mariuspod** [comment]
too outdated pr

**Pull request closed without merging**
