### PR TITLE
[EXP-20-192] sentry support and automatic capturing of unhandled exceptions

### PR DESCRIPTION
**Pull request by mariuspod**
brownie captures all exceptions when invoked via `brownie run` cli commands and doesn't propagate them to the caller. As a consequence, there is no working auto-capturing of exceptions with sentry when running a brownie script.

To fix the root cause, I've added a cli flag to brownie run `-r` that will raise exceptions instead of swallowing them: [https://github.com/mariuspod/brownie/commit/e8739dd5f4114577aa2073e9ddea47d24204c45e](https://github.com/mariuspod/brownie/commit/e8739dd5f4114577aa2073e9ddea47d24204c45e)\
I'll create a PR for brownie once I have a running test :sweat_smile:\
Until then, I've linked the SHA to my brownie fork.

For our threads I've noticed that due to the `threading.Event` that we're using, any exceptions are not raised to the caller until the event is unlocked. That's why I'm setting it to done in the `except` and re-raising to the caller.

Tested with sentry (in prod) :sweat_smile:

### CODE REVIEW

**Comment by mariuspod** [comment]
@banteg 
what do you think ? It's running fine capturing exceptions on our staging host hooked up with sentry.

**Comment by banteg** [comment]
is there any way to avoid bare `except`?

**Comment by mariuspod** [comment]
@banteg here's a minimal example demonstrating the issue with the thread exceptions. If you uncomment the `self._done.set()` in the except block the main thread will hang indefinitely without exiting.
Note the explicit `os.exit(1)` which is needed to prevent the default python finalization code which can also fail in some cases as discussed here: https://stackoverflow.com/questions/45267439/fatal-python-error-and-bufferedwriter

if you agree, I'd create an annotation method so we can just wrap our existing threading code with that instead of code-duplications.

```python
import threading
import os

class A:
    def __init__(self):
        self._done = threading.Event()
        self._thread = threading.Thread(target=self.work, daemon=True)

    def start(self):
        if not self._thread._started.is_set():
            print("starting thread")
            self._thread.start()

    def wait(self):
        self._done.wait()
        if self._has_exception:
            print("thread exception")
            os._exit(1)

    def work(self):
        print("work")
        try:
            1/0
            self._done.set()
        except Exception as e:
            print(e)
            self._has_exception = True
            self._done.set()
            raise e

a = A()
a.start()
a.wait()
```

**Comment by mariuspod** [comment]
> is there any way to avoid bare `except`?

I think it's useful to push them through here so they become visible in sentry and then we can handle them properly in the underlying code. The typed exceptions which are raised are already passed correctly to sentry. This is just for the unhandled ones.

**Review by banteg — APPROVED** [review]

**Pull request merged**
