### PR TITLE
fix: update APY support for crypto pools

### PR DESCRIPTION
**Pull request by dudesahn**

### CODE REVIEW

**Comment by dudesahn** [comment]
@x48-crypto plz review my changes, I think this should fix APY calc for triCrypto but there may be a more elegant/correct way to do it

**Comment by banteg** [comment]
Side note: I suggest a deeper refactor of APY calculations. The use of lower-level API here is unjustified, I suggest using `yearn.prices.magic.get_price` when you need a price of anything. For example, ETH-like and BTC-like don't account for some newer pools, there is a better logic available and there is no need replicate it.

**Comment by jstashh** [comment]
@dudesahn just been testing this - looks good apart from one issue. We're getting an incorrect value of ~6% because it's using the price from WBTC to calculate the apy, even with your change. This is the problematic line:

```
base_asset = WBTC if btc_like else WETH if eth_like else lp_token if crypto_pool else underlying_coins[0]
```

We go through this list of conditions sequentially - looking at `if btc_like` first. The logic for `btc_like` is `btc_like = any([coin in BTC_LIKE for coin in underlying_coins])`. This unintentionally evaluates to true for the crypto pool because one of the `underlying_coins` is WBTC. 

To fix this we should change the `base_asset` calculation to be: 

```
base_asset = lp_token if crypto_pool else WBTC if btc_like else WETH if eth_like else underlying_coins[0]
```
so we check if it's in the crypto pool before we check if it's btc_like. 

With that change we get this, which looks better:

Screenshot 2021-06-22 at 00 21 56

I agree with @banteg that this file should be tidied up so we don't duplicate pricing logic, maybe we can follow up with a separate PR

**Comment by dudesahn** [comment]
Closing this PR based on feedback from banteg and jstash, and also the fact that I deleted my fork of the repo when the CI was going crazy. New PR is here #70

**Pull request closed without merging**
