### PR TITLE
feat: add optimism network support 

### LINKED ISSUE #369: feat: add optimism network
See #242 for what is needed to add a new network to the exporter.

### PR DESCRIPTION
**Pull request by DarkGhost7**
# List to implement 

Fixes #369

**Network**:  Optimism
**Chain ID**:  10

>Make sure all points are addressed. This is a list for adding full network support to the exporter.

To configure the network correctly you must add the following constants:

- in ./yearn/networks.py:
- [x] specify the chainid in the same way as the others.
- [x] specify a network label in `Networks.label`.

- in ./yearn/constants.py:
- [x] specify Treasury address. (if Yearn has a treasury contract deployed) This would be the rewards() address of any vault.
- [x] specify Multisig address. This would be the governance() address of any vault
- [x] specify Strategist Multisig address. (if Yearn has a SMS deployed) This would be the management() address of any vault.

- in ./yearn/prices/constants.py:
- [x] add weth address to `tokens_by_network`.
- [x] add the {{network}} gas token address to `wrapped_gas_coin` field.
- [x] add usdc address to `tokens_by_network`.
- [x] add dai address to `tokens_by_network`.
- [x] configure `stablecoins` using popular + "safe" stablecoins on the chain.

- in ./yearn/multicall2.py:
- [x] specify the appropriate multicall2 contract address.

- in ./yearn/ironbank.py:
- [x] add ironbank deployment address

- in ./yearn/v2/registry.py
- [x] add v2 vault registry

- in yearn/yearn.py
- [x] add v2 vault registry and ironbank registry

- in ./yearn/prices/chainlink.py:
- [x] specify any chainlink feeds available on the chain in `feeds`.
- [x] specify the chainlink registry address in `registries` if applicable, or specify None if not applicable.

- in ./yearn/prices/compound.py
- [x] add ib comptroller

- in ./yearn/prices/constants.py: `ib_snapshot_block_by_network`
- [x] specify if any the start block of Ironbank on this network or specify '1' if not applicable.

- in ./yearn/prices/uniswap/v2.py:
- [x] specify the factory and router address for any important uni v2 forks on the chain.

- in ./yearn/prices/uniswap/v3.py:
- [x] add info about uni v3 deployed on network

- in ./yearn/utils.py:
- [x] specify `BINARY_SEARCH_BARRIER` as 0 if all historical data is available. If historical data not available due to a network upgrade/etc, specify the first block of the available historical data.

- in ./yearn/middleware/middleware.py:
- [x] specify `BATCH_SIZE` of approx 1 day based on avg block times on the chain.

- in ./scripts/historical-exporter.py:
- [x] configure `end` to equal the date + hour of deployment for the first Yearn product on the chain.
- [x] configure `data_query`. See `mapping` in ./yearn/outputs/victoria/output_helper.py to figure out the metric to specify based on what type of product was the first deployed on the chain.

- in ./scripts/historical-treasury-exporter.py:
- [x] configure `end` to equal the date + hour of deployment for the Yearn Treasury on the chain.
- [x] configure `data_query` using the existing networks as an example.

- in ./scripts/historical-sms-exporter.py:
- [x] configure `end` to equal the date + hour of deployment for the Strategist Multisig on the chain.
- [x] configure `data_query` using the existing networks as an example.

You also need to set up containers for each exporter on the new chain. This is a little more complicated but you can use existing containers as an example:
- [x] define common envs for the chain
- [x] add one new service entry for forwards exporter
- [x] add one new service entry for historical exporter
- [x] add one new service entry for treasury exporter
- [x] add one new service entry for historical treasury exporter
- [x] add one new service entry for sms exporter
- [x] add one new service entry for historical sms exporter
- [x] add one new service entry for wallet exporter
- [x] add one new service entry for transactions exporter
- [x] adapt entrypoint.sh

in ./Makefile: Set up network specific make command.
- [x] network
- [x] logs-network

There still may be some things I'm missing, so it's important to test to make sure everything works!

Once you've handled everything above, type `make <network> && make <logs-network>` into your terminal replacing network with your network name at the project root. The network specific exporters will start running in docker and any exceptions will show in your terminal. If there are no exceptions, and everything appears to be running smoothly then it should be working correctly.

- [x] yes I have tested it and it is running as expected

### CODE REVIEW

**Comment by DarkGhost7** [comment]
It seems like Trident is deployed on optimism instead of the normal sushi which is a v2 fork. Does this address need to go anywhere?

**Comment by DarkGhost7** [comment]
Just missing ychad addy

**Comment by DarkGhost7** [comment]
> Just missing ychad addy
added

**Review by mariuspod — APPROVED** [review]
Very cool work!

Added some additions for:
- ib
- v2 registry
- some constants
- some fixes and workarounds

All exporters are up :rocket:
the transactions_exporter still has some temporary issues which should self-heal once we have some transactions.

**Pull request merged**
