### PR TITLE
[EXP-95-295] GH Actions Testing Workflows

### PR DESCRIPTION
**Pull request by BobTheBuidler**

### CODE REVIEW

**Comment by BobTheBuidler** [comment]
This is a draft I'm using for testing. Do not merge. Updates to come.

**Comment by BobTheBuidler** [comment]
Questioning the validity of this test:
image

2 markets can have vastly different prices for the same asset without either price technically being incorrect. Therefore, I propose removing this test entirely from the test suite. @mariuspod @banteg what do you think here?

**Comment by mariuspod** [comment]
@BobTheBuidler
could we rewrite the test for a token with more or less the same price in different markets for a given block and a different price at another block ?

**Comment by BobTheBuidler** [comment]
> @BobTheBuidler could we rewrite the test for a token with more or less the same price in different markets for a given block and a different price at another block ?

per discussion with @mariuspod we will pass on this, but will add a test for liquidity-based-pricing on minor-fixes branch folling merge of #295

**Review by jstashh — APPROVED** [review]

**Pull request merged**
