### PR TITLE
feat: add arbitrum exporters #354

### PR DESCRIPTION
**Pull request by ImmanuelSegol**
#354

- [ ]  define common envs for the chain
- [ ]  add one new service entry for forwards exporter
- [ ]  add one new service entry for historical exporter
- [ ]  add one new service entry for treasury exporter
- [ ]  add one new service entry for historical treasury exporter
- [ ]  add one new service entry for sms exporter
- [ ]  add one new service entry for historical sms exporter
- [ ]  add one new service entry for wallet exporter
- [ ]  add one new service entry for transactions exporter
- [ ]  adapt entrypoint.sh

### CODE REVIEW

**Comment by DarkGhost7** [comment]
should be mostly done here #363

**Comment by DarkGhost7** [comment]
Since arbitrum is mostly done maybe you can work on adding optimism if you want to take over #367 this would help as well @ImmanuelSegol.

**Comment by ImmanuelSegol** [comment]
> Since arbitrum is mostly done maybe you can work on adding optimism if you want to take over #367 this would help as well @ImmanuelSegol.

Oh ok I can take optimism

want to open a issue for that and assign me ?

**Comment by BobTheBuidler** [comment]
@ImmanuelSegol going to close this PR and you can open a new one when you've got Optimism ready. Thanks for your help.

**Pull request closed without merging**
