### PR TITLE
[EXP-80-280] feat(partners): add sturdy on fantom

### PR DESCRIPTION
**Pull request by iris112**

### CODE REVIEW

**Comment by BobTheBuidler** [comment]
While testing this PR, I found an issue with batch calls on Fantom. 
I've implemented a quick fix for this issue in #281.
Placing this on hold until 281 is merged.

**Comment by BobTheBuidler** [comment]
@iris112 just merged #279 , could you rebase on master and then I can merge? 
Thanks

**Comment by iris112** [comment]
> @iris112 just merged #279 , could you rebase on master and then I can merge? Thanks
@BobTheBuidler You can merge this PR now. Thanks

**Review by BobTheBuidler — APPROVED** [review]
lgtm, merging

**Pull request merged**
