### PR TITLE
feat: veyfi exporter

### PR DESCRIPTION
**Pull request by DarkGhost7**
Related issue # (if applicable):

### What I did:
@0xkofee build the veYFI exporter and it's working for both fwds and backwords exporting. Added the veYFI dashboard to yearn/veYFI

### How to verify it:
'make veyfi'

### Checklist:
- [x] I have tested it locally and it works
- [x] I have included any relevant documentation for the repo maintainers
- [ ] (If fixing a bug) I have added a test to the test suite to test for this particular bug

### CODE REVIEW

**Comment by BobTheBuidler** [comment]
I think "exporters/veyfi" should be added to the full command list earlier in the makefile as well

**Comment by BobTheBuidler** [comment]
Or maybe the better option would just be to have `make up` call `make veyfi` so we don't have to consider how to disable veyfi on alt chains

**Comment by DarkGhost7** [comment]
> Or maybe the better option would just be to have `make up` call `make veyfi` so we don't have to consider how to disable veyfi on alt chains

Yah I have been thinking about how best to do this since its only on ETH

**Comment by BobTheBuidler** [comment]
lgtm, pooshing!

**Review by BobTheBuidler — APPROVED** [review]

**Pull request merged**
